### PR TITLE
documentation/ZENKO-1408_remove_duplicate_ingress_configuration

### PR DESCRIPTION
**Pull request by wabernat**
This PR removes a duplicated section in the Installation Guide

This PR fixes ZENKO-1408

### CODE REVIEW

**Comment by ghost** [comment]
There were the following issues with this Pull Request

* Commit: 97e79b355ccadbb065f03837918c3771d5bae349
  - ✖ message may not be empty
  - ✖ type may not be empty


You may need to [change the commit messages][ref] to comply with the repository contributing guidelines.

--------

🤖 This comment was generated by [**commitlint[bot]**][repo]. Please report issues [here][issues].

Happy coding!

[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/z0al/commitlint-bot
[issues]: https://github.com/z0al/commitlint-bot/issues

**Comment by wabernat** [comment]
@bert-e reset

**Comment by ghost** [comment]
There were the following issues with this Pull Request

* Commit: 97e79b355ccadbb065f03837918c3771d5bae349
  - ✖ message may not be empty
  - ✖ type may not be empty
* Commit: 761f338982987a45bbb952d43d54d76cdb36d74e
  - ✖ message may not be empty
  - ✖ type may not be empty


You may need to [change the commit messages][ref] to comply with the repository contributing guidelines.

--------

🤖 This comment was generated by [**commitlint[bot]**][repo]. Please report issues [here][issues].

Happy coding!

[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/z0al/commitlint-bot
[issues]: https://github.com/z0al/commitlint-bot/issues

**Review by ssalaues — APPROVED** [review]

**Comment by wabernat** [comment]
@bert-e approve

**Review by giacope — APPROVED** [review]

**Comment by ssalaues** [comment]
@bert-e

**Pull request merged**
