### PR TITLE
documentation: ZENKO-1549_add_GET_bucket_list_objects_v2

### PR DESCRIPTION
**Pull request by wabernat**
This PR introduces the GET Bucket List Objects V2 API to the Zenko documentation. 

It fixes ZENKO-1549.

This was a straight-up copy of the same API from S3 Connector. If you know of any functional Delta, please advise.

### CODE REVIEW

**Comment by wabernat** [comment]
@bert-e approve

**Comment by wabernat** [comment]
Squashed commits.

**Review by JianqinWang — COMMENTED** [review]
I'm not familiar with the necessary structure of the files, but are the files
`docs/Reference/bucket_operations/get_bucket_list_objects_v2.rst` and
`docs/docsource/Reference/bucket_operations/get_bucket_list_objects_v2.rst` duplicate? Do they both need to be present?

**Comment by wabernat** [comment]
Good spot, @JianqinWang. I am having restructuring fun with Git. Will inspect.

**Comment by wabernat** [comment]
@bert-e reset

**Review by JianqinWang — APPROVED** [review]

**Review by ssalaues — APPROVED** [review]

**Pull request merged**
