### PR TITLE
improvement: ZENKO-3864 bump cloudserver to 8.2.19

### PR DESCRIPTION
**Pull request by naren-rajendran**
Bump cloudserver to 8.2.19

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Review by alexanderchan-scality — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by alexanderchan-scality** [comment]
ping

**Review by alexanderchan-scality — APPROVED** [review]

**Pull request merged**
