### PR TITLE
imprv: ZENKO 1775 reduce quota test flakiness

### PR DESCRIPTION
**Pull request by dora-korpar**
Decreases location quota test flakiness by reducing quota limit (to reduce amount of requests needed to fill a bucket), and creating more unique test buckets.

### CODE REVIEW

**Review by JianqinWang — APPROVED** [review]

**Review by philipyoo — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Review by ssalaues — APPROVED** [review]

**Review by tmacro — APPROVED** [review]
You'll need to rebuild the orbit-sim image to pull down the changes

**Comment by ssalaues** [comment]
@bert-e bypass_build_status

**Comment by dora-korpar** [comment]
@bert-e approve

**Comment by ssalaues** [comment]
@bert-e status

**Comment by dora-korpar** [comment]
The build passed here with an image including the orbit-simulator changes: https://eve.devsca.com/github/scality/zenko/#/builders/2/builds/3731

**Comment by dora-korpar** [comment]
@bert-e approve

**Comment by ssalaues** [comment]
@bert-e bypass_build_status

**Pull request merged**
