### PR TITLE
feature: ZENKO-1760 prometheus endpoint via healthcheck server

### PR DESCRIPTION
**Pull request by jonathan-gramain**
Expose Prometheus metrics via a new route in healthcheck server, for
the following backbeat components:

- lifecycle conductor
- lifecycle bucket processor
- lifecycle object processor
- queue populator
- replication data processor
- replication status processor
- garbage collector

### CODE REVIEW

**Review by tmacro — APPROVED** [review]

**Comment by ssalaues** [comment]
@jonathan-gramain would this require a new backbeat image once your other PRs are merged?

**Comment by jonathan-gramain** [comment]
@ssalaues Eventually, yes, but it should still work as before without a new image, just the new pod metrics wouldn't be scraped. We can build the image for the next RC as usual I think.

**Comment by jonathan-gramain** [comment]
On the other hand it might help to spot performance issues during testing, could be worth building an image for this reason.

**Review by ssalaues — APPROVED** [review]

**Comment by ssalaues** [comment]
I'm ok with either waiting for the RC or building now. Likely we'll be building an RC sometime this week.

**Comment by jonathan-gramain** [comment]
@bert-e approve

**Pull request merged**
