### PR TITLE
improvement: bump backbeat

### PR DESCRIPTION
**Pull request by ssalaues**
**What does this PR do, and why do we need it?**
Finally image bump before RC

### CODE REVIEW

**Review by tmacro — APPROVED** [review]

**Review by JianqinWang — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by ssalaues** [comment]
@bert-e approve

**Comment by ssalaues** [comment]
Failed on a known flaky test. Otherwise passed all other E2E tests
https://eve.devsca.com/github/scality/zenko/#/builders/4/builds/6771

**Comment by ssalaues** [comment]
@bert-e bypass_build_status

**Comment by rahulreddy** [comment]
@bert-e bypass_build_status

**Pull request merged**
