### PR TITLE
feature/ZENKO-558/Ref_Guide_initial_merge Initial commit for Reference Guide source

### PR DESCRIPTION
**Pull request by wabernat**
This merge imports the Zenko Reference Guide from the Flare source. 

fixes #ZENKO-558

Please do not review in depth. Say yes. Then file tickets.

### CODE REVIEW

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
@bert-e approve

**Comment by wabernat** [comment]
@bert-e help

**Comment by wabernat** [comment]
@bert-e approve

**Review by tmacro — APPROVED** [review]

**Review by JianqinWang — APPROVED** [review]

**Review by ssalaues — APPROVED** [review]

**Comment by wabernat** [comment]
@bert-e approve

**Comment by wabernat** [comment]
If anything more is needed to merge, please advise. If one of you folks needs to give Bert-E a nudge, please do so.

**Pull request merged**
