### PR TITLE
Bump pensieve-api 1.4.0

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Review by welansari — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Comment by francoisferrand** [comment]
@nicolas2bert  I don't think this should actually go in 2.5 : pensieve-api `1.4` should go in `2.6` branch, e.g. artesca `1.7`...

**Comment by nicolas2bert** [comment]
Already bumped

**Pull request closed without merging**
