### PR TITLE
documentation: ZENKOIO-96 Fix API Headings

### PR DESCRIPTION
**Pull request by wabernat**
This PR does a whole lot of reorganization and orthographic fixes on the Reference guide.

- Requests and responses given heading status.
- API calls & responses rendered in monospace.
- Tables fixed to be legible in both HTML and PDF outputs.
- Backbeat and Prometheus rendered more like the other APIs in the book.

This fixes #ZENKOIO-96

**Note:** This is a big one. Sorry for the volume to review. I've discussed this
with the DE, and further work is required on ordering Backbeat and Prometheus
calls into a user-friendly format (i.e., as being accessible through Cloudserver
API, rather than as freestanding APIs). I'll create another ticket for this set
of edits.

### CODE REVIEW

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
@bert-e reset

**Review by bennettbuchanan — APPROVED** [review]

**Comment by wabernat** [comment]
@bert-e approve

**Review by dora-korpar — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Pull request merged**
