### PR TITLE
Documentation/zenko 2350 support for 3 servers

### PR DESCRIPTION
**Pull request by wabernat**
This PR adds the changes requested in ZENKO-2350 concerning support for 3-node clusters.

### CODE REVIEW

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
@bert-e force_reset

**Comment by wabernat** [comment]
@bert-e approve

**Comment by wabernat** [comment]
@rahulreddy

**Review by rahulreddy — APPROVED** [review]

**Pull request merged**
