### PR TITLE
ZENKO-4561: grant inprog read permission

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Review by rahulreddy — APPROVED** [review]

**Review by rachedbenmustapha — APPROVED** [review]

**Comment by francoisferrand** [comment]
please don't merge like this, this PR includes lots of commits which are not related!

**Comment by alexanderchan-scality** [comment]
@francoisferrand will be splitting into separate PRs;
the current state includes debug commits in  attempt to stabilize the tests

**Review by naren-rajendran — APPROVED** [review]

**Review by rachedbenmustapha — APPROVED** [review]

**Comment by alexanderchan-scality** [comment]
ping

**Pull request merged**
