### PR TITLE
Merge branch 'development/1.0' into improvement/doc-ZENKO-1293-add-lo…

### PR DESCRIPTION
**Pull request by wabernat**
…gos2

This PR fixes the logos in the documentation.

This PR fixes ZENKO-1293

### CODE REVIEW

**Comment by wabernat** [comment]
@bert-e approve

**Review by philipyoo — APPROVED** [review]

**Review by JianqinWang — APPROVED** [review]

**Comment by ssalaues** [comment]
@wabernatScality This was already done in your previous PR https://github.com/scality/Zenko/pull/451 and is merged into both development/1.0 and development/1.1

**Review by alexanderchan-scality — APPROVED** [review]

**Comment by ssalaues** [comment]
@bert-e wait

**Comment by wabernat** [comment]
Apparently, this build is duplicative. Withdrawing.

**Pull request closed without merging**
