### PR TITLE
ZENKO-3659 use latest Cloudserver image 8.2.15

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Comment by nicolas2bert** [comment]
ping

**Review by miniscruff — APPROVED** [review]

**Review by alexanderchan-scality — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Comment by nicolas2bert** [comment]
@bert-e reset

**Comment by nicolas2bert** [comment]
@bert-e reset

**Comment by nicolas2bert** [comment]
@bert-e reset

**Comment by miniscruff** [comment]
ping

**Pull request merged**
