### PR TITLE
documentation: ZENKOIO-49_Bad_Links_in_Ref_Guide

### PR DESCRIPTION
**Pull request by wabernat**
This PR fixes some bad links I found on one page of the reference guide. We need it because broken links are bad. 

This fixes #ZENKOIO-49

### CODE REVIEW

**Comment by wabernat** [comment]
I need a version check override on aisle 7.

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
@bert-e reset

**Review by bennettbuchanan — APPROVED** [review]

**Review by ssalaues — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Comment by wabernat** [comment]
@bert-e approve

**Pull request merged**
