### PR TITLE
Cosmos improvements and updates

### PR DESCRIPTION
**Pull request by ssalaues**
**What does this PR do, and why do we need it?**
- Disables the initial ingestion from starting immediately (basis for pause/resume)
- Define threading options in CR so they're more accessible (they were available before but had to be added in manually)
- Omit unused values from the Cosmos CR (makes it easier to read/debug/etc)
- Updates the tests to manually trigger ingestion by patching the CR and triggering the job

**Which issue does this PR fix?**

ZENKOIO-132
ZENKOIO-133

### CODE REVIEW

**Review by JianqinWang — APPROVED** [review]

**Comment by anurag4DSB** [comment]
Tried the changes with AWS OOB, works perfectly as intended.
`kubectl edit cosmos` allows you to set `suspend: false` 
This way we can control when the OOB ingestion starts.

**Review by anurag4DSB — APPROVED** [review]

**Comment by ssalaues** [comment]
@anurag4DSB Setting `suspend: false` will indeed enable the cron job. However if you want to manually trigger an ingestion right away you can set `triggerIngestion: true`. Both options work independently from each other.

**Comment by ssalaues** [comment]
@bert-e wait

**Comment by tmacro** [comment]
@bert-e bypass_build_status

**Comment by anurag4DSB** [comment]
@ssalaues Thank you for the clarification. I understand cronjob schedule and once we set `triggerIngestion: true`, it will trigger ingestion immediately.

what if we need to trigger another ingestion manually? Do we set `triggerIngestion: false` and then`true` again?

Also, what would you recommend? Changing these options under `rclone` or individual `jobTemplate`?

**Comment by ssalaues** [comment]
> what if we need to trigger another ingestion manually? Do we set `triggerIngestion: false` and then`true` again?

Yeah that will work. It can be useful for testing. This can be done all in one command as well so you don't have to edit every time.
 
> Also, what would you recommend? Changing these options under `rclone` or individual `jobTemplate`?

I'm not sure I understand. Everything you should change is listed under `spec:`.

**Comment by ssalaues** [comment]
@bert-e approve

**Pull request merged**
