### PR TITLE
Bugfix/zenko 1295 s3utils image

### PR DESCRIPTION
**Pull request by ssalaues**
**What does this PR do, and why do we need it?**
Fixes issues with templating errors for the maintenance cron jobs

**Which issue does this PR fix?**

ZENKO-1295

**Special notes for your reviewers**:

### CODE REVIEW

**Review by JianqinWang — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
We should probably make our CI to deploy with maintenance and debug enabled so that we can catch it before we get the build out.

**Comment by ssalaues** [comment]
@bert-e wait

**Comment by ssalaues** [comment]
@bert-e reset

**Comment by ssalaues** [comment]
@bert-e help

**Pull request merged**
