### PR TITLE
Improvement/zenko 4230 add missing dataconsumer permissions

### PR DESCRIPTION
**Pull request by ghost**
Missing permissions for the Data Consumer leads to 500 errors in Artesca UI.

From the build:

```
  iam policies - cloudserver - AssumeRoleWithWebIdentity - DeleteObjectVersion
    ✓ should be able to perform DeleteObjectVersion on all buckets for storage manager role (101ms)
    ✓ should be able to perform DeleteObjectVersion on all buckets for storage account owner role (120ms)
    ✓ should be able to perform DeleteObjectVersion on all buckets for data consumer role (126ms)
  iam policies - cloudserver - AssumeRoleWithWebIdentity - GetBucketReplication
    ✓ should be able to perform GetBucketReplication on all buckets for storage manager role (153ms)
    ✓ should be able to perform GetBucketReplication on all buckets for storage account owner role (144ms)
    ✓ should be able to perform GetBucketReplication on all buckets for data consumer role (152ms)
  iam policies - cloudserver - AssumeRoleWithWebIdentity - GetBucketLifecycle
    ✓ should be able to perform GetBucketLifecycle on all buckets for storage manager role (134ms)
    ✓ should be able to perform GetBucketLifecycle on all buckets for storage account owner role (118ms)
    ✓ should be able to perform GetBucketLifecycle on all buckets for data consumer role (113ms)
  iam policies - cloudserver - AssumeRoleWithWebIdentity - PutBucketLifecycle
    ✓ should be able to perform PutBucketLifecycle on all buckets for storage manager role (109ms)
    ✓ should be able to perform PutBucketLifecycle on all buckets for storage account owner role (128ms)
    ✓ should be able to perform PutBucketLifecycle on all buckets for data consumer role (119ms)
  iam policies - cloudserver - AssumeRoleWithWebIdentity - PutBucketReplication
    ✓ should be able to perform PutBucketReplication on all buckets for storage manager role (139ms)
    ✓ should be able to perform PutBucketReplication on all buckets for storage account owner role (141ms)
    ✓ should be able to perform PutBucketReplication on all buckets for data consumer role (162ms)
```

### CODE REVIEW

**Comment by ghost** [comment]
ping

**Review by XinLi0207 — APPROVED** [review]

**Review by ghost — APPROVED** [review]
lgtm

**Review by watsaqat — APPROVED** [review]

**Pull request merged**
