### PR TITLE
Release 2.10.0

### PR DESCRIPTION
**Pull request by francoisferrand**
- Bump MongoDB 6.0.12
- Bump Backbeat to 8.6.49
- Bump zenko-ui 3.0.3
- mongo node sync alert implementation
- mongo node sync test alert implementation
- Bump pensieve-api 1.6.2
- Bump zenko-operator 1.6.2
- Release Zenko 2.10.0

Issue: ZENKO-4893

### CODE REVIEW

**Review by benzekrimaha — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by francoisferrand** [comment]
There is an issue with PRA, but it is not used in 2.10 ; which we need to release now, and the broken feature will not be used in that context

**Pull request merged**
