### PR TITLE
improvement: ZENKO-3127 set image pull policy

### PR DESCRIPTION
**Pull request by rahulreddy**
Set image pull policy to `IfNotPresent`

### CODE REVIEW

**Comment by rahulreddy** [comment]
There are other references like the zookeeper operator
```
          command:
          - zookeeper-operator
          imagePullPolicy: Always

```
Should I change this as well?

**Comment by miniscruff** [comment]
> 
> 
> There are other references like the zookeeper operator
> 
> ```
>           command:
>           - zookeeper-operator
>           imagePullPolicy: Always
> ```
> 
> Should I change this as well?

I think so

**Comment by NicolasT** [comment]
I'm a bit confused as to why we have to (ever) specify an `imagePullPolicy`. The default policy is `IfNotPresent`, *except* if the tag is `latest`, in which case it is `Always`. So, setting a (custom) `imagePullPolicy` (likely setting it to `Always` for non-`latest` tags) is a sign of a flawed delivery pipeline (note, I'm aware that's *not* what this PR is doing). Except if there's a security policy which dictates to use `Always` (which would then always verify the digest of the local image with the remote one, preventing image cache injection attacks).
So, instead of setting this to `IfNotPresent`, wouldn't it be better to rely on the (sensible) defaults and not specify anything at all?

**Comment by rachedbenmustapha** [comment]
Already relies on the default value provided by zenko-operator which is "if not present"

**Pull request closed without merging**
