### PR TITLE
ZENKO-4796: pull zenko UI image from ghcr.io

### PR DESCRIPTION
**Pull request by ChengYanJin**
**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Review by JBWatenbergScality — APPROVED** [review]
LGTM !

**Review by francoisferrand — CHANGES_REQUESTED** [review]
We are already doing the change on Zenko, accross all components : will actually be done there, as part https://scality.atlassian.net/browse/PTFE-1376 (esp. it needs to be done accross all branches)

On the other hand,
* all tags must be migrated from registry.scality.com to ghcr (allow building older versions), as documented in platform engineering's blog
* you are bumping to newer release, should be a separate & explicit bump [ghcr migration should be NOOP]

**Comment by ChengYanJin** [comment]
> We are already doing the change on Zenko, accross all components : will actually be done there, as part https://scality.atlassian.net/browse/PTFE-1376 (esp. it needs to be done accross all branches)
> 
> On the other hand,
> 
> * all tags must be migrated from registry.scality.com to ghcr (allow building older versions), as documented in platform engineering's blog
> * you are bumping to newer release, should be a separate & explicit bump [ghcr migration should be NOOP]

Hello @francoisferrand, it should be good now. We migrated all the existing tags to ghcr and separated the bump zenko-ui to a dedicate commit ;)

**Review by francoisferrand — CHANGES_REQUESTED** [review]
this ticket is about migration, which is handled separately (in Zenko4800)
→ please create a separate ticket & PR (possibly after #2061 is merged) to track the bump, if you need it

(Jira is not just to have a number and please bert-e, it is really to document the work we need to do: you don't need the registry migration to bump to 2.2.9, but you problably have many other reasons: like to deliver fixes already merged in Zenko-UI and which "block" product issues)

**Comment by ChengYanJin** [comment]
close because duplicate with Zenko4800

**Pull request closed without merging**
