### PR TITLE
ZENKO-4550: bump dependencies

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
* zenko-operator => 1.5.12
* pensieve-api => 1.4.4

**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Review by rahulreddy — APPROVED** [review]

**Comment by alexanderchan-scality** [comment]
ping

**Review by naren-rajendran — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Comment by rahulreddy** [comment]
development/2.7 is broken even w/o these changes and currently blocking 2.6 release, I am exceptionally bypassing this PR

**Pull request merged**
