### PR TITLE
ZENKO-3943 - add test on mongodb alerts

### PR DESCRIPTION
**Pull request by lavigne958**
Added tests on mongodb alerts.
Updated alerts if needed.
Fix typo in dashboard.

### CODE REVIEW

**Comment by lavigne958** [comment]
hey bert-e

**Comment by lavigne958** [comment]
hey bert-e

**Review by jbertran — APPROVED** [review]

**Review by jbertran — APPROVED** [review]

**Review by welansari — APPROVED** [review]

**Pull request merged**
