### PR TITLE
bf: safely handle multiple ingestion buckets

### PR DESCRIPTION
**Pull request by ssalaues**
**What does this PR do, and why do we need it?**
This safely handles when an additional ingestion bucket is created. It does this
by using a label with the bucket value that is referenced when attempting to
`ApplyChanges`.

**Which issue does this PR fix?**
ZENKO-1756

### CODE REVIEW

**Review by tmacro — APPROVED** [review]

**Review by dora-korpar — APPROVED** [review]

**Comment by rachedbenmustapha** [comment]
@ssalaues about the PascalCase adjustment, it's only needed if you want to make the functions/methods exported to other packages - uppercase denotes public visibility. It's generally discouraged to export more than the strict minimum as a "public interface", to make maintainer's lives easier when trying not to break API/ABIs. My suggestion would be to leave camelCase in place unless we want to publicly support these APIs.

**Comment by ssalaues** [comment]
@RachedBenMustapha yeah those are good points. It was originally a mix of the two and I wasn't entirely sure of the significance of either. I'll revert it camelCase then.

**Comment by ssalaues** [comment]
@bert-e approve

**Comment by ssalaues** [comment]
@bert-e status

**Pull request merged**
