### PR TITLE
ft: Unify charts with Orbit

### PR DESCRIPTION
**Pull request by ssalaues**
This allows Orbit to be enabled by default which is our normal for swarm and cloudserver.

### CODE REVIEW

**Comment by vrancurel** [comment]
just asking: why do we need to enable it by default ?

**Comment by ssalaues** [comment]
@vrancurel It's because our default in s3 cloudserver is to have it enabled along with having enabled by default in the docker stack as well. Was speaking with @rahulreddy and was saying this should be our default configuration for Zenko.

**Comment by NicolasT** [comment]
@ssalaues May want to amend the typo in the commit message.

**Comment by ssalaues** [comment]
Oops! Good catch. Fixed the typo in commit.

**Pull request merged**
