### PR TITLE
documentation: ZENKO-2322_x-amz-location-constraint_GET_object_header

### PR DESCRIPTION
**Pull request by wabernat**
adds documentation for x-amz-location-constraint header for GET object API.

Fixes ZENKO-2322

### CODE REVIEW

**Comment by wabernatScality** [comment]
.

**Comment by wabernat** [comment]
@bert-e approve

**Comment by wabernatScality** [comment]
.

**Comment by wabernat** [comment]
@bert-e reset

**Comment by dora-korpar** [comment]
Changes look good to me, but I believe shortly after we introduced the concept of location constraints, we made a conscious decision not to document the 'x-amz-location-constraint' because we wanted to keep location constraints at the level of buckets. Just want to confirm that  we actually do want to document it now

**Comment by wabernat** [comment]
@bert-e wait

**Comment by wabernat** [comment]
@dora-korpar 
1. I think this might be the wrong branch. Check out 967, and sorry for the absolute confusuion.
2. This is in response to a request by @jonathan-gramain. You guys should talk this out (over there) or in https://scality.atlassian.net/browse/ZENKO-2322

**Comment by dora-korpar** [comment]
Got it, looks like it's for a replication use-case, so makes sense 👍

**Comment by wabernat** [comment]
Correct branch is for approval at https://github.com/scality/Zenko/pull/967

Closing this branch.

**Pull request closed without merging**
