### PR TITLE
bug(zenko-566): Re-enable Prometheus Tests

### PR DESCRIPTION
**Pull request by tmacro**
Re-add basic prometheus tests with them temporarily disabled while PIPDEP-538 is resolved.

### CODE REVIEW

**Comment by vrancurel** [comment]
Shall we move that in there https://github.com/scality/Zenko/tree/master/charts/zenko/templates/ in a tests subfolder ? because it makes sense as a Helm test

**Comment by giacomoguiulfo** [comment]
@tmacro What's the status on this?

**Comment by tmacro** [comment]
@giacomoguiulfo Currently the test doesn't work, not sure of the thought process behind it, so I'm not sure how to fix.

**Comment by giacomoguiulfo** [comment]
Closing this in favor of #192.

**Pull request closed without merging**
