### PR TITLE
ZENKO-3349: update count items script

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
**What does this PR do, and why do we need it?**

update s3utils image version
* count-items script fix: parse content-length as number before running calculations

**Which issue does this PR fix?**

fixes ZENKO-3349

**Special notes for your reviewers**:

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
ping

**Comment by alexanderchan-scality** [comment]
ping

**Review by miniscruff — APPROVED** [review]

**Review by naren-rajendran — APPROVED** [review]

**Pull request merged**
