### PR TITLE
Improvement/zenko 3980 bump cloudserver and zenko

### PR DESCRIPTION
**Pull request by ghost**
Introduces the fix for https://scality.atlassian.net/browse/ARTESCA-3648. Also bumps Zenko version.

### CODE REVIEW

**Comment by ghost** [comment]
ping

**Comment by ghost** [comment]
ping

**Review by anurag4DSB — APPROVED** [review]

**Review by KillianG — APPROVED** [review]

**Comment by ghost** [comment]
ping

**Pull request merged**
