### PR TITLE
documentation: ZENKO-1458 Orbit Lifecycle chapter missing from RST

### PR DESCRIPTION
**Pull request by wabernat**
This PR reintroduces a section and attendant image files that were dropped in the initial translation from Flare. 

fixes ZENKO-1458

### CODE REVIEW

**Comment by wabernat** [comment]
@bert-e approve

**Review by nicolas2bert — APPROVED** [review]
Good catch!  As we talked about, I am going to update screenshot once this fix is merged. :)

**Review by ssalaues — APPROVED** [review]

**Comment by wabernat** [comment]
If anyone can unstick this, I'd appreciate the assist. I don't have VPN access, so I can't mess with eve.

**Comment by ssalaues** [comment]
@wabernatScality it hasn't gone through because of the branch name. It needs to be one of `feature/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*`

**Pull request merged**
