### PR TITLE
feature: add pause/resume route

### PR DESCRIPTION
**Pull request by ssalaues**
**What does this PR do, and why do we need it?**
Adds a route that will return the current status of the location cron on GET. The state can be modified on POST. Included is a README update with the routes and example usage with curl.

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Review by JianqinWang — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Review by rachedbenmustapha — COMMENTED** [review]
I can see why exposing a REST endpoint for suspend/resume would be useful for manual operation (testing, troubleshooting, ...), but in the global context of Zenko, wouldn't it make sense to monitor the Zookeeper keys that backbeat-api already uses to manage suspend/resume state, and react to changes?

**Comment by ssalaues** [comment]
Yeah that would make sense to have only one universal source of truth to read from. I'll leave that decision to the powers that be since this was the design choice made at the last minute as an attempt to squeeze it in for 1.2.0 GA.

**Comment by dora-korpar** [comment]
@bert-e bypass_author_approval

**Review by vrancurel — APPROVED** [review]

**Comment by vrancurel** [comment]
@bert-e bypass_author_approval

**Comment by vrancurel** [comment]
@bert-e help

**Pull request merged**
