### PR TITLE
Setting up nightly stage on CI

### PR DESCRIPTION
**Pull request by tcarmet**
Successfully tested, nightly images are properly pulled and installed on the Zenko repo. Here's a build link https://eve.devsca.com/github/scality/zenko/#/builders/4/builds/664

Feel free to ask some changes and everything

### CODE REVIEW

**Comment by tcarmet** [comment]
The pre-merge build is not working, but I think it is due to backbeat's new version (if I rollback it works)

Maybe @tmacro knows a little bit more about this

**Comment by Zempashi** [comment]
In the theory of releng engeneering "science" there is no so called "nightly". There is only a pipeline:
```
test 1 => action 1 => test2 => action2 => test3 =>action3
```
On ring, we have something similar:
```
pre-merge => merge => post-merge
```
The fact that post-merge run nightly is for performance sake. We have to take care that having the nightly will not shot ourself
"oh the nightly hasn't run today, I can't work", "I will wait for the nightly to run to do something specific and long running"

**Comment by tcarmet** [comment]
Sure thing!
I'm personnally not a fan of nightly builds (because you have to wait the next morning for results) and you're right about the "Oh I can't work, no build was triggered" I've been there.

I think the nightly build was requested to have some kind of early news about the end2end tests, and avoid having bad news just before a release, or making a PR on this project.

I'm closing this PR until I have further discussion with everyone (you, SF, releng)

**Comment by Zempashi** [comment]
No no, don't close this PR. You misunderstand me. Just call it differently that nightly. We are just bare human, and believe it to occur at night (asynchronously, which is bad), but nothing technical prevent it run synchronously at each merge/tag/whatever_but_not_commit

**Comment by tcarmet** [comment]
OH got you! sorry about that @Zempashi :smile:  

I'll rename the stage and also make some modification into the tags on s3, backbeat..., using the sha1 or something like that. Remove the nightly name to avoid confusions, and I'll reopen a PR according to that.

**Pull request closed without merging**
