### PR TITLE
Bugfix/zenko 3269 fix pdf image widths

### PR DESCRIPTION
**Pull request by cathydossantospinto**
Taking up on William's work and ticket [ZENKO-3269](https://scality.atlassian.net/browse/ZENKO-3269)! He fixed the PDF image size on the Installation Guide, and I carried on the work with the Operation Guide. 
-> Note that the size of some HTML images changed, but it doesn't prevent the readability.

### CODE REVIEW

**Comment by cathydossantospinto** [comment]
> # Incorrect fix version
> 
> The `Fix Version/s` in issue [ZENKO-3269](https://scality.atlassian.net/browse/ZENKO-3269) contains:
> 
>     * `1.2.1`
> 
> 
> Considering where you are trying to merge, I ignored possible hotfix versions and I expected to find:
> 
>     * `1.2.3`
> 
>     * `1.3.0`
> 
>     * `2.0.0`
> 
> 
> Please check the `Fix Version/s` of [ZENKO-3269](https://scality.atlassian.net/browse/ZENKO-3269), or the target
> branch of this pull request.

Fixed!

**Comment by cathydossantospinto** [comment]
> # Conflict
> 
> A conflict has been raised during the creation of
> integration branch `w/2.0/bugfix/ZENKO-3269_fix_PDF_image_widths` with contents from `w/1.3/bugfix/ZENKO-3269_fix_PDF_image_widths`
> and `development/2.0`.
> 
> **I have not created the integration branch.**
> 
> Here are the steps to resolve this conflict:
> 
> ```shell
>  $ git fetch
>  $ git checkout -B w/2.0/bugfix/ZENKO-3269_fix_PDF_image_widths origin/development/2.0
>  $ git merge origin/w/1.3/bugfix/ZENKO-3269_fix_PDF_image_widths
>  $ # <intense conflict resolution>
>  $ git commit
>  $ git push -u origin w/2.0/bugfix/ZENKO-3269_fix_PDF_image_widths
> ```

Conflict resolved!

**Review by lucieleonard — APPROVED** [review]
Check the PDFs partially (not really bothered about those) -- okay
Checked the whole HTML and the images look ok to me.

**Comment by cathydossantospinto** [comment]
Closing this PR because of the wrong branch name. The prefix `bugfix` prevents the bypass of python-tests for the build. Reopening a new PR #1245 with the right prefix `documentation` in the branch name.

**Pull request closed without merging**
