### PR TITLE
Bump versions to PREGA

### PR DESCRIPTION
**Pull request by tmacro**
## Cloudserver CHANGELOG
* Merge branch 'feature/ZENKO-925-increaseMetricsExpiry' into q/8.0
* ft: ZENKO-925 increase metrics expiry to 24hrs
* ZNC-22: DOC: Add developer bootstrap guide
* Merge branch 'bugfix/ZENKO-903/getBucketListOnReport' into q/8.0
* Merge branch 'bugfix/ZENKO-916-doNotReplicateACLChange' into q/8.0
* bf: ZENKO-903 add tests for report itemCount
* improvement: update arsenal
* bf: ZENKO-922 add redis disconnect tests
* bf: ZENKO-916 do not replicate ACL change
* Merge remote-tracking branch 'origin/bugfix/S3C-1586/listing_while_upgrade' into w/8.0/bugfix/S3C-1586/listing_while_upgrade
* Do not parse list entries from MD6.4.7

## Backbeat CHANGELOG:
* Merge branch 'feature/ZENKO-925-increaseMetricsExpiry' into q/8.0
* ft: increase metrics expiry window to 24hrs
* bf: ZENKO-917 publish consumer current offset to zk

### CODE REVIEW

**Comment by tmacro** [comment]
@bert-e e wait

**Comment by tmacro** [comment]
@bert-e wait

**Comment by ssalaues** [comment]
Can we add the backbeat change log to that commit just like the cloudserver one?

**Comment by ssalaues** [comment]
@tmacro Okay so we're doing RC5 instead of PREGA. Can you rename where appropriate please?

**Pull request closed without merging**
