### PR TITLE
Release Zenko 2.4.31 (with less flakiness?)

### PR DESCRIPTION
**Pull request by nicolas2bert**
Increasing timeout (using the default one ie 15 minutes).
It might decrease flakiness but increase the testing time.

### CODE REVIEW

**Comment by nicolas2bert** [comment]
ping

**Review by rahulreddy — APPROVED** [review]

**Review by naren-rajendran — APPROVED** [review]

**Comment by rahulreddy** [comment]
Waiting for https://github.com/scality/Zenko/tree/w/2.5/feature/ZENKO-4355-2 to finish the CI

**Review by rachedbenmustapha — APPROVED** [review]

**Comment by rahulreddy** [comment]
Closing as https://github.com/scality/Zenko/pull/1734 got merged

**Pull request closed without merging**
