### PR TITLE
Documentation/zenko 3098 fixed broken link

### PR DESCRIPTION
**Pull request by thomasj-tech**
**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**
Fixed a broken link in the first paragraph of Configuring Logical Volumes.rst

fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Comment by lucieleonard** [comment]
@wabernatScality  do we need to hit "Deploy"?

**Review by wabernat — APPROVED** [review]

**Review by tcarmet — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Comment by wabernatScality** [comment]
.

**Comment by wabernatScality** [comment]
.

**Pull request merged**
