### PR TITLE
documentation: ZENKO-1667_remove_scality-zenko_instances

### PR DESCRIPTION
**Pull request by wabernat**
This PR removes "Scality Zenko" in the four places it appeared in the documentation

This fixes ZENKO-1667

### CODE REVIEW

**Comment by wabernat** [comment]
@bert-e approve

**Review by smaffulli — COMMENTED** [review]
LGTM

**Review by smaffulli — APPROVED** [review]
LGTM

**Comment by wabernatScality** [comment]
@bert-e wait

**Review by ssalaues — APPROVED** [review]

**Comment by ssalaues** [comment]
@bert-e bypass_build_status

**Pull request merged**
