### PR TITLE
feat(ZENKO-1361): Mock Azure in end to end tests

### PR DESCRIPTION
**Pull request by tmacro**
Replace Azure with github.com/Azure/Azurite/ for pre-merge tests. Still run against the real Azure for our nightly dev builds.

### CODE REVIEW

**Comment by tmacro** [comment]
@bert-e approve

**Comment by tmacro** [comment]
@bert-e reset

**Review by ssalaues — APPROVED** [review]

**Review by giacope — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by tmacro** [comment]
@bert-e approve

**Comment by tmacro** [comment]
@bert-e reset

**Pull request merged**
