### PR TITLE
ZENKO-4101: add mongodb configserver service

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
**What does this PR do, and why do we need it?**

* add mongodb configserver service resource
* modify mongos sts to point mongodb configserver service instead of a specific node

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Review by francoisferrand — CHANGES_REQUESTED** [review]
This should IMHO be added to the `patches`, not directly in the charts...
otherwise it will be difficult to ensure we don't break anything when upgrading to newer version of the charts.

**Review by francoisferrand — APPROVED** [review]

**Comment by francoisferrand** [comment]
do we need to also keep the changes "applied" ? are the patches not applied automatically during Zenko image build?

**Comment by alexanderchan-scality** [comment]
@francoisferrand the patches are not applied on build time. the changes are always applied to the charts. 
patching in build time can be something I can do after the RC release.

**Review by miniscruff — APPROVED** [review]

**Comment by alexanderchan-scality** [comment]
ping

**Pull request merged**
