### PR TITLE
ZENKO-2236 fixing read the docs build

### PR DESCRIPTION
**Pull request by tcarmet**
We broke the read the docs build because the requirements.txt
file needs to be along side the sphinx conf file (conf.py)

### CODE REVIEW

**Review by tmacro — APPROVED** [review]

**Review by dashagurova — COMMENTED** [review]
There is another problem (latex_title is not defined), I fixed it for 1.2 but not for 1.1
Since you want to merge to 1.1 I will add the fix for 'latex_title' as well :)

**Comment by dashagurova** [comment]
@bert-e approve

**Review by dashagurova — APPROVED** [review]

**Pull request merged**
