### PR TITLE
Documentation/zenko 3656/remove s3 endpoint

### PR DESCRIPTION
**Pull request by John-VanHook**
**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Review by nloewensen — APPROVED** [review]
Commands for CLI actions would need to be reviewed by a developer (not me ;) )

**Review by cathydossantospinto — APPROVED** [review]

**Comment by John-VanHook** [comment]
Niels said: 

`I think we should add an explanation here of what will happen if the location is still in use by a bucket. Honestly I have not tried but will the deletion fail or succeed?`

Tech Pubs: We have no way to test this. Can you look into it and come back with an answer?

**Pull request merged**
