### PR TITLE
bugfix: ZENKO-2634_fix_bad_1.20_docs_links

### PR DESCRIPTION
**Pull request by wabernat**
This PR fixed documentation errors noticed while uploading Zenko 1.2.0 docs to website. 

Specifically: 
* Fixed bad link structures.
* Updated year variable to 2020
* Fixed tables that were running off the PDF margins.

fixes #ZENKO-2634

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Comment by wabernat** [comment]
It's really a shame that I can't merge. Bert-E expects the new number (1.2.1), but it hasn't been updated on Jira (1.2.0 or nothing). This problem happens every time we upgrade. I've asked a bunch of times that we fix it, and nothing ever changes.

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
@tcarmet Can you please check and fix why the Jira version check happens this way?

**Review by tcarmet — APPROVED** [review]

**Pull request merged**
