### PR TITLE
documentation: ZENKOIO-123_fix_all_links

### PR DESCRIPTION
**Pull request by wabernat**
Manually tested, repaired, and upgraded all links.
Updated conf.py version variables.
Consolidated a couple of topics.

This PR fixes, improves, adds, and makes nicer all the links in the doc. We need it because wrong things are bad, and bad things are wrong. 

This fixes #ZENKOIO-123

### CODE REVIEW

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
@bert-e approve

**Review by jonathan-gramain — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Comment by wabernat** [comment]
@bert-e reset

**Comment by ssalaues** [comment]
@bert-e bypass_build_status

**Comment by wabernat** [comment]
Dammit!

**Pull request merged**
