### PR TITLE
Improvement/zenko 3163/fix images for alpha3

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
**What does this PR do, and why do we need it?**
fixes images for alpha3
**Which issue does this PR fix?**
ZENKO-3163
fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Review by anurag4DSB — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
@alexanderchan-scality Did something happen with backbeat that you had to revert?

**Review by miniscruff — COMMENTED** [review]
What about the e2e file?

**Comment by alexanderchan-scality** [comment]
@rahulreddy https://github.com/scality/backbeat/pull/1415, backbeat queuePopulator pod had an issue in whici it is not loading extensions, and subsequent calls to set up the extensions resulted in a hard crash.

**Review by miniscruff — APPROVED** [review]

**Pull request merged**
