### PR TITLE
documentation/ZEKOIO-59_remove_old_tutorials

### PR DESCRIPTION
**Pull request by wabernat**
This PR removes outdated .md tutorials. I also updated one screengrab, and fiddled with text in install guide/NFS setup (discovered issues while working a related project)

This PR fixes #ZENKOIO-59

### CODE REVIEW

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
@bert-e approve

**Comment by wabernatScality** [comment]
@bert-e bypass_jira_check

**Comment by wabernat** [comment]
@rahulreddy Can you do a Jira bypass on this ticket? I'm getting no traction from Releng.

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
@bert-e reset

**Comment by wabernat** [comment]
Updated the branch in error. Re-doing.

**Pull request closed without merging**
