### PR TITLE
bugfix: ZENKO-3801 bump vault version to 8.3.2.3

### PR DESCRIPTION
**Pull request by ghost**
This PR bumps the vault version to fix ARTESCA-3036

### CODE REVIEW

**Comment by ghost** [comment]
ping

**Comment by ghost** [comment]
ping

**Review by KillianG — APPROVED** [review]

**Review by welansari — APPROVED** [review]

**Comment by ghost** [comment]
@JBWatenbergScality Should I upgrade the Zenko version here or is it fine to merge the PR as it is now, since we will not include this fix in 1.2.1?

**Comment by JBWatenbergScality** [comment]
> @JBWatenbergScality Should I upgrade the Zenko version here or is it fine to merge the PR as it is now, since we will not include this fix in 1.2.1?

I think it can be done in another PR

**Comment by ghost** [comment]
ping

**Pull request merged**
