### PR TITLE
ZENKO-4202: bump zenko

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Review by naren-rajendran — APPROVED** [review]

**Comment by alexanderchan-scality** [comment]
ping

**Comment by alexanderchan-scality** [comment]
ping

**Review by ChengYanJin — APPROVED** [review]
Thanks!

**Comment by alexanderchan-scality** [comment]
ping

**Pull request merged**
