### PR TITLE
Test SOSAPI PUTs with a bucket having a dot in its name

### PR DESCRIPTION
**Pull request by ghost**
This allows to test that the custom route is accepting such buckets.

For now we have failures - to be merged once we bump ZKOP to the latest version

```
Failures:

1) Scenario: PUT routes for SOSAPI configuration files # features/sosapi.feature:32
   ✔ Before # hooks/Logger.ts:36
   ✔ Before # hooks/versionTags.ts:6
   ✔ Before # common/hooks.ts:20
   ✔ Given a "Non versioned" bucket with dot # common/common.ts:104
   ✔ When I PUT the "invalid" "capacity.xml" XML file # steps/sosapi.ts:49
   ✖ Then the request should be "not accepted" # steps/sosapi.ts:69
       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

       true !== false

           + expected - actual

           -true
           +false

           at Zenko.<anonymous> (/ctst/steps/sosapi.ts:72:12)
   ✔ After # hooks/Logger.ts:60

2) Scenario: PUT routes for SOSAPI configuration files # features/sosapi.feature:34
   ✔ Before # hooks/Logger.ts:36
   ✔ Before # hooks/versionTags.ts:6
   ✔ Before # common/hooks.ts:20
   ✔ Given a "Non versioned" bucket with dot # common/common.ts:104
   ✔ When I PUT the "invalid" "system.xml" XML file # steps/sosapi.ts:49
   ✖ Then the request should be "not accepted" # steps/sosapi.ts:69
       AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

       true !== false

           + expected - actual

           -true
           +false

           at Zenko.<anonymous> (/ctst/steps/sosapi.ts:72:12)
   ✔ After # hooks/Logger.ts:60
```

Issue: ZENKO-4889

### CODE REVIEW

**Comment by ghost** [comment]
Must be merged after ZENKO-4899 (with latest ZKOP).

**Review by KillianG — APPROVED** [review]

**Review by francoisferrand — APPROVED** [review]

**Pull request merged**
