### PR TITLE
documentation/ZENKO-2322_x-amz-location-constraint_GET_object_header

### PR DESCRIPTION
**Pull request by wabernat**
added x-amz-location-constraint header for GET object API.

This PR adds brief documentation for the x-amz-location-constraint GET object header. It also adds "mk8s 2.4 or later" to the cluster setup instructions.

This resolves ZENKO-2322 and addresses the simple part of ZENKOIO-138.

### CODE REVIEW

**Comment by wabernatScality** [comment]
.

**Review by jonathan-gramain — COMMENTED** [review]
I'm good with the changes.

Since they apply to Zenko 1.1, if we're still supporting it, we could have this PR targeted at development/1.1 instead right?

**Comment by wabernat** [comment]
Probably. I'm having a bit of trouble targeting stabilization branches this week...

**Comment by wabernat** [comment]
development/1.1 is protected

**Comment by wabernatScality** [comment]
.

**Comment by wabernat** [comment]
@bert-e approve

**Review by jonathan-gramain — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Pull request merged**
