### PR TITLE
Improvement/zenko 2792 capture s3 c reference improvements

### PR DESCRIPTION
**Pull request by wabernat**
This ginormous PR restructures the Zenko Reference document to have a similar structure to the S3 Connector reference, adding more extensive API information, a command reference with s3 and s3api commands, a unified Error Message section,  plus numerous small "fixits" 

This addresses ZENKO-2792

Reviewers: Please review the overall organization/TOC-level changes, not the fine details (unless something jumps out at you). Also make sure that the sections pertaining to your area of expertise are OK if you have the time.

### CODE REVIEW

**Comment by wabernatScality** [comment]
.

**Review by tmacro — APPROVED** [review]

**Comment by wabernat** [comment]
@tcarmet Can you fix or bypass the test issue on this ticket?

**Review by tcarmet — APPROVED** [review]

**Pull request merged**
