### PR TITLE
rel: Releasing Zenko 1.2.0-rc.3

### PR DESCRIPTION
**Pull request by tcarmet**

### CODE REVIEW

**Review by rahulreddy — APPROVED** [review]

**Comment by anurag4DSB** [comment]
The tests have been failing at this part:

```
command timed out: 1200 seconds without output running . ../eve/scripts/only-docs.sh
make -e VERBOSE=1 test
, attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=1720.100433
```

This is the place till where we have success: https://github.com/scality/Zenko/blob/71ebfee6438360b9dc0e4aff5188addca677a38f/tests/zenko_tests/node_tests/backbeat/tests/crr/awsBackend.js#L43

I made 2 branches for reverting backbeat and cloud server to check where is the issue:

- “feature/ZENKO-2405-checkCloudserver”
- “feature/ZENKO-2405-checkBackbeat”

The one where I reverted backbeat, passes:

> https://eve.devsca.com/github/scality/zenko/#/builders/4/builds/12657
> feature/ZENKO-2351-checkBackbeat


I think we need to investigate more in backbeat.

**Comment by anurag4DSB** [comment]
You might want to update this: https://github.com/scality/Zenko/blob/d2d861c224af655a1c647d11e3a16f696fb941af/kubernetes/zenko/Chart.yaml#L2
Otherwise you might face an issue like this: 
https://github.com/scality/Zenko/issues/983

**Review by tmacro — APPROVED** [review]

**Comment by tcarmet** [comment]
done @anurag4DSB
Thanks for the heads up :)

**Pull request merged**
