### PR TITLE
Bump zenko-ui version to 1.4.8

### PR DESCRIPTION
**Pull request by JBWatenbergScality**
**What does this PR do, and why do we need it?**

**Which issue does this PR fix?**

fixes #<ISSUE>

**Special notes for your reviewers**:

### CODE REVIEW

**Review by alexanderchan-scality — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by francoisferrand** [comment]
@JBWatenbergScality you need to rebase this branch on top of latest Zenko commits, overwise build will never pass.

**Comment by francoisferrand** [comment]
Done in https://github.com/scality/Zenko/pull/1647

**Pull request closed without merging**
