### PR TITLE
docs(README.md): fix broken link to minikube docs

### LINKED ISSUE #368: Minikube docs link broken
In the readme under Testing Zenko, the "Zenko Single-Node Kubernetes" link 404s.

Should the link be https://github.com/scality/Zenko/blob/development/1.1/docs/minikube.md ?

### PR DESCRIPTION
**Pull request by giacope**
**What does this PR do, and why do we need it?**

Fixes a broken link in the README.md

**Which issue does this PR fix?**

fixes #368

**Special notes for your reviewers**:

Two liner 🎉

### CODE REVIEW

**Review by JianqinWang — APPROVED** [review]

**Review by nicolas2bert — APPROVED** [review]

**Review by ssalaues — APPROVED** [review]

**Comment by giacomoguiulfo** [comment]
@bert-e 	wait

**Review by philipyoo — APPROVED** [review]

**Comment by giacope** [comment]
@bert-e 	reset

**Comment by giacope** [comment]
@bert-e 	help

**Comment by giacope** [comment]
@bert-e 	force_reset

**Comment by giacope** [comment]
@bert-e 	help

**Comment by ssalaues** [comment]
@bert-e reset

**Comment by ssalaues** [comment]
@bert-e force_reset

**Comment by giacope** [comment]
@bert-e 	force_reset

**Pull request merged**
