### PR TITLE
ZENKO-4731: bump vault version

### PR DESCRIPTION
**Pull request by benzekrimaha**
# Generated by copilot
This pull request includes a minor update to the `solution/deps.yaml` file in the `vault:` section. The `tag` value has been updated from `8.7.9` to `8.7.11`, indicating an upgrade to a newer version of the software.

# By author 
This PR is bumping vault version adressing both : https://scality.atlassian.net/browse/VAULT-538 and https://scality.atlassian.net/browse/VAULT-537

### CODE REVIEW

**Comment by benzekrimaha** [comment]
ping

**Comment by benzekrimaha** [comment]
ping

**Comment by benzekrimaha** [comment]
ping

**Review by francoisferrand — APPROVED** [review]

**Review by fredmnl — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Pull request merged**
