### PR TITLE
ZENKO-2254 review resource usage on CI tests

### PR DESCRIPTION
**Pull request by tcarmet**
Reviewing pod resource usage, I felt like we were asking too much RAM resource.

I reviewed each resource request with the actual usage when the test are running. I'm still giving more than I should, but this will help us save some space in our infra.

### CODE REVIEW

**Review by JianqinWang — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Comment by tcarmet** [comment]
/wait

don't want to merge this PR yet, I feel like it's causing more trouble, I'm gonna run multiple builds just to make sure

**Comment by tcarmet** [comment]
Closing this PR as today we don't have a resource issue and this still needs some work to be good.

**Pull request closed without merging**
