### PR TITLE
ft: ZENKO-3321-update-vault-v8.2.0-alpha.2

### PR DESCRIPTION
**Pull request by ilkescality**
Updating vault image, introduces limited IAM users & policies functionality.

### CODE REVIEW

**Comment by anurag4DSB** [comment]
ping

**Review by tcarmet — APPROVED** [review]

**Review by anurag4DSB — CHANGES_REQUESTED** [review]
I am currently in the process of testing this image with Zenko + metalk8s one node cluster. Only once tested this can be merged. Otherwise, we will get this in, in 2.0.0-alpha.5

**Comment by anurag4DSB** [comment]
I tested on one node Zenko + metalk8s and the vault image on my laptop. This vault image does not have the latest code. 
We can close this PR.
We will be aiming for Zenko 2.0.0-alpha.5 with a new image.

**Review by anurag4DSB — APPROVED** [review]

**Comment by anurag4DSB** [comment]
Update: The new vault image has the latest changes, my zenko cluster upgrade had failed(for some reason it showed the new tag though)

**Comment by ilkescality** [comment]
Asking for re-reviews as I made few changes after/during rebasing per changes in https://github.com/scality/Zenko/commit/0d5bec1b6f6451696299766a99a16e249e758832 (such as removing version from `solution/zenkoversion.yaml` as we no longer having them there). Also adding @RachedBenMustapha for review to make sure it looks good.

**Review by anurag4DSB — APPROVED** [review]

**Review by rachedbenmustapha — APPROVED** [review]

**Review by alexanderchan-scality — APPROVED** [review]

**Pull request merged**
